---
#
# Playbook enabling NXAPI on devices running in VIRL using new `network_cli`
# connection method.
#
# Author: Quinn Snyder, Systems Architect | Enterprise Southwest .:|:.:|:. Cisco Systems
# Date: 2019-10-14
# Version: 0.2a
#
- name: Enabling NXAPI on N9Kv switches in VIRL
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Enable NXAPI with HTTP (8080) and HTTPS (8443)
    nxos_nxapi:
      http_port: 8080
      http: yes
      https_port: 8443
      https: yes

  - name: Enable NXAPI to use-vrf management
    nxos_config:
      lines: nxapi use-vrf management
