---
#
# Initial testing of Ansible automation on NXOS9000v in VIRL
# Demonstration of multihost playbook leveraging variables at both the host and group level
# Does not use a "pause" function to demonstrate that the rollback functionality does occur within the playbook
#
# Author: Quinn Snyder, Systems Architect | Enterprise Southwest .:|:.:|:. Cisco Systems
# Date: 2019-10-14
# Version: 0.2a
#
- name: Demonstration of automation of Nexus 9000v devices running in VIRL using Ansible
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: Enable NXAPI with HTTP (8080) and HTTPS (8443)
      nxos_nxapi:
        http_port: 8080
        http: yes
        https_port: 8443
        https: yes

    - name: Enable NXAPI to use-vrf management
      nxos_config:
        lines: nxapi use-vrf management

    - name: Enable the OSPF feature on each switch
      nxos_feature:
        feature: ospf
        state: enabled
        provider: "{{ nxapi }}"

    - name: Configure interfaces to be in "UP" state
      with_items: "{{ interface_info }}"
      nxos_interface:
        description: 'Configured by Ansible'
        interface: "{{ item.int_name }}"
        admin_state: up
        provider: "{{ nxapi }}"

    - name: Configure IP addresses on interfaces
      nxos_ip_interface:
        interface: "{{ item.int_name }}"
        version: v4
        state: present
        addr: "{{ item.ip }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxapi }}"
      with_items: "{{ interface_info }}"

    - name: Enable OSPF process on each switch
      nxos_ospf:
        ospf: "{{ ospf_process }}"
        state: present
        provider: "{{ nxapi }}"

    - name: Configure OSPF on interfaces
      nxos_interface_ospf:
        interface: "{{ item.int_name }}"
        ospf: "{{ ospf_process }}"
        area: "{{ ospf_area }}"
        cost: "{{ ospf_cost }}"
        provider: "{{ nxapi }}"
      with_items: "{{ interface_info }}"

    - name: Make sure peer loopback0 is seen in routing table for OSPF
      nxos_command:
        commands: show ip route ospf
        wait_for: result[0] contains "{{ peer_loop }}"
      register: result
      ignore_errors: true

    - name: Revert if OSPF routes not found
      import_role:
        name: revert
      when: result|failed
